name = "savaspin-casino-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=savaspin-casino.com.gr"
HMAC_KEY = "eb75e0941dbd448fad3afb7139155b159e2669039b8f4288119c1ed1a57d85bd"
COOKIE_NAME = "hkd"
PLAY_PATH = "discover"
BUTTON_ID = "p0202188d7f94797c2d9457f1ba432d23"
GATE_SALT = "d2cd5b93b7d580b3"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0l3d"
CTA_SELECTOR = ".play-button"
